.github/workflows/main.yaml, CHANGELOG.md, configuration.go, credentials/credentials.go, fga_test.go, go.mod, go.sum
- Fix incorrectly applying client_credentials validation to api_token cred method [openfga/sdk-generator#21](https://github.com/openfga/sdk-generator/pull/21)
- Target go 1.19
- Bump golang.org/x/net
- Use [govulncheck](https://go.dev/blog/vuln) in CI to check for issues
=> release: v0.0.3

client/client.go
Wrap some of the SDK client request (such as SdkClientReadAssertionsRequest) to have an interface version.  This allows better ability to test and mock by users of the SDK
Close https://github.com/openfga/go-sdk/issues/23
=> chore: change SDK ClientRequest to be interface

api_open_fga.go, internal/utils/utils.go, oauth2/internal/token.go, oauth2/internal/token_test.go
Add in retry logic for oauth failure
Close https://github.com/openfga/go-sdk/issues/20
=> fix: add retry logic to oauth

client/client.go
OpenFgaClient did not satisfy SdkClient interface as there are discrepancy in ReadAuthorizationModel and ReadLatestAuthorizationModel method
Close https://github.com/openfga/go-sdk/issues/34
=> fix: OpenFgaClient should satisfy SdkClient interface

api_open_fga.go, client/client.go, client/client_test.go
Allow empty string for store id and auth model id
Close https://github.com/openfga/go-sdk/issues/36
=> fix: allow empty string as ulid

client/client.go
Miss a path we do not allow empty ulid
Follow up on https://github.com/openfga/go-sdk/pull/37
=> fix: miss a branch where we do not allow empty ulid

client/client.go, client/client_test.go
Client not taking in details for option and body in list stores/read changes etc. In addition, read auth model does not check and error when auth model is id string is empty
Close https://github.com/openfga/go-sdk/issues/41
Close https://github.com/openfga/go-sdk/issues/42
=> fix: client option + body not respected

CHANGELOG.md, configuration.go, model_assertion.go, model_authorization_model.go, model_check_request.go, model_contextual_tuple_keys.go, model_create_store_request.go, model_difference.go, model_expand_request.go, model_list_objects_request.go, model_relation_reference.go, model_tuple_keys.go, model_type_definition.go, model_write_assertions_request.go, model_write_authorization_model_request.go
=> release(v0.2.3): with various client fixes

api_open_fga_test.go, credentials/credentials.go
- Generator PR by @harper: https://github.com/openfga/sdk-generator/pull/237
=> fix: resolve a bug in `NewCredentials`

README.md, api_open_fga_test.go, credentials/credentials.go
Add OAuth2 client credentials support
Add an optional scope parameter and make the audience parameter optional.
https://github.com/openfga/sdk-generator/issues/255
https://github.com/openfga/sdk-generator/pull/256
=> feat: oauth2 client credentials support

oauth2/clientcredentials/clientcredentials.go, oauth2/oauth2.go
remove canonical imports from oauth2 packages
https://github.com/openfga/go-sdk/issues/63
=> fix: remove canonical import path from oauth2 packages

api_open_fga.go, client/client_test.go, example/Makefile
Adds the Deletes property to the test to ensure that we don't pass this when it is empty. Given that we don't match on body this isn't really much gain but it will help to ensure we maintain this in future if we improve testing.
Also copies across some recent changes from the sdk-generator repo/api docs
Part of https://github.com/openfga/sdk-generator/issues/299
Generated from https://github.com/openfga/sdk-generator/pull/306
=>  chore: add test to cover not sending empty array when other has data

CHANGELOG.md, configuration.go, example/example1/go.mod
- fix: don't escape HTML characters in conditions when marshalling a model
=> release: v0.3.5

README.md
closes https://github.com/openfga/go-sdk/issues/48
=> fix: The README example in Go-SDK uses inconsistent name.

client/client.go, client/client_test.go
Removes the read auth model call in BatchCheck/Write and replaces it with checking and returning an invalid model id error and then returning an invalid auth error if one arises.
Part of https://github.com/openfga/sdk-generator/issues/314
=> fix: do not call read auth model on batchcheck and write

oauth2/internal/token.go, oauth2/internal/token_test.go
We currently retry every request that fails on a credential request, we should only retry on 429 or 5xx errors (this is what Java and Python do).
=> fix: only retry on client credential requests that are 429 or 5xx

CHANGELOG.md, README.md, configuration.go, example/example1/go.mod
Changes:
* #102 
* #101 
⚠️ **BREAKING CHANGE** ⚠️ 
This version removes the `StoreId` from the API client configuration. Instead, the `StoreId` parameter 
must now be passed to each of the API methods that require a store ID. 
**If you are using `api_open_fga.go` directly, you will now need to pass the `StoreId` parameter.**
https://github.com/openfga/sdk-generator/pull/369
=> release: v0.4.0

example/example1/example1.go
While testing ListUsers for internal usage, I noticed a couple small typos in the README.
=> fix: ListUsers readme typos

README.md, client/client.go, configuration.go
Copies across some changes from the sdk-generator repo
https://github.com/openfga/sdk-generator/pull/371
https://github.com/openfga/sdk-generator/pull/372 (will close https://github.com/openfga/go-sdk/issues/104)
=> fix: fixes to config and readme

CHANGELOG.md, configuration.go, example/example1/go.mod
```
- fix: correctly set HTTPClient
- chore!: remove excluded users from ListUsers response
BREAKING CHANGE:
This version removes the `ExcludedUsers` field from the `ListUsersResponse` and `ClientListUsersResponse` structs,
for more details see the [associated API change](https://github.com/openfga/api/pull/171).
```
=> release: v0.5.0

README.md
missing "." before Execute() in chained commands: Options(options)Execute()
=> chore(docs): fix typo in README.md

README.md
ClientTupleKey type had changed, but readme file is still &[]ClientTupleKey
- [√] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [√] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [√] The correct base branch is being used, if not `main`
- [√] I have added tests to validate that the change in functionality is working as expected
=> chore: fix out-dated document of ClientTupleKey

CHANGELOG.md, configuration.go, example/example1/go.mod, internal/telemetry/telemetry.go
- feat: support OpenTelemetry metrics reporting
- feat!: support for sending the consistency parameter to the read, check, list users, list objects, and expand endpoints.
BREAKING CHANGE:
When the generator converts enums in the open API definition, by default it removes the type prefix. For example, `TYPE_NAME_UNSPECIFIED` is converted to a const named `UNSPECIFIED`. This leads to potential collisions with other enums, and as the consistency type is a new enum, we finally got a collision (was just a matter of time).
The fix for this is to specify `"enumClassPrefix": true` in the generation config. This will then include the class name on the const name, which resoles collision issues. This means any enum value, such as `INT` now becomes `TYPENAME_INT`. The main impact of this is the …
=> release: v0.6.0

CHANGELOG.md, README.md, example/example1/go.mod
- refactor(OpenTelemetry): move configuration API into public package namespace (#122)
- docs(OpenTelemetry): initial documentation and example (#123)
=> release: v0.6.1

telemetry/telemetry.go, telemetry/telemetry_test.go
Fixes data race on `TelemetryInstances`.
- #134 
- Fixes #135 
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> fix: fix data race of TelemetryInstances variable

telemetry/metrics.go, telemetry/metrics_test.go
Fix data race issue in `metrics.go` caused by unlocked access to the `Counters` and `Histograms` maps.
Similar to fix provided in #136 
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> fix: Fix data race issue on metrics Counters and Histograms

client/client.go
…#144
References: [#452](https://github.com/openfga/sdk-generator/pull/452)
Fixes: #144 
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> fix: support marshaling client.ClientWriteResponse

client/client.go
Adds the getter/setter methods for Authorization Model ID and Store ID onto the `SdkClient` interface so that when generating a mock from  this client they can be used.
=> fix: update client interface with store and model getter/setter

api_client.go, api_client_test.go
Ensure that a default telemetry instance is created when creating an API client directly.
When a `Configuration` is created via `NewConfiguration`, we ensure that a default telemetry is created if not specified. However, when creating a `Configuration` directly as shown in [#466](https://github.com/openfga/sdk-generator/issues/466), no telemetry is created. This causes `telemetry.Get` to create a new telemetry instance on each call (e.g., each API call), which causes the map to grow unbounded.
This change ensures that a default Telemetry instance is created when creating a new `APIClient`.
https://github.com/openfga/sdk-generator/issues/466
=> fix: api client should set default telemetry if not specified

client/client.go, client/client_test.go
Fix: Do not ignore request level storeId override in non-transactional write
Currently, the request level store ID is ignored in non-transactional write requests, resulting in the error "storeId is required and must be specified". This PR fixes the issue by passing the storeId to the WriteExecute call.
This PR
- passes the request level storeId to the WriteExecute call
- extends the unit test covering the storeId override case
=> fix: Do not ignore request level storeId in non-transactional write

client/client.go
Fix for start time not checked in request body
Addresses: https://github.com/openfga/sdk-generator/issues/483
Also backported to sdk-generator: https://github.com/openfga/sdk-generator/pull/484
=> fix: populate start_time in request

README.md
Resolves issue in README from Issue #483 for go-sdk.  Reflects StartTime in Body rather than Options for ReadChanges
https://github.com/openfga/sdk-generator/issues/483
=> docs: Update README for StartTime in Body for ReadChanges

README.md, client/client.go, client/client_test.go, example/example1/example1.go
Adds `Context` and `ContextualTuples` support to `Assertions` in the `OpenFGAClient`
https://github.com/openfga/sdk-generator/issues/449
https://github.com/openfga/api/pull/185
=> feat: support assertions with context and contextual tuples

.openapi-generator/FILES, CHANGELOG.md, client/client.go, client/client_test.go, configuration.go, example/example1/go.mod, example/opentelemetry/go.mod
```
- feat: support assertions with context and contextual tuples (#169)
- fix: populate start_time in request (#166)
```
=> release: v0.6.5

CHANGELOG.md, configuration.go, example/example1/go.mod, example/opentelemetry/go.mod
Release 0.6.6 for go-sdk including:
- feat: fix and improve retries and rate limit handling. (https://github.com/openfga/go-sdk/pull/176)
The SDK now retries on network errors and the default retry handling has been fixed
for both the calls to the OpenFGA API and the API Token Issuer for those using ClientCredentials
The SDK now also respects the rate limit headers (`Retry-After`) returned by the server and will retry the request after the specified time.
If the header is not sent or on network errors, it will fall back to exponential backoff.
- feat: retry on network errors when calling the token issuer (https://github.com/openfga/go-sdk/pull/182)
- feat: add upport for server-side BatchCheck (https://github.com/openfga/go-sdk/pull/187)
- chore: log retry attempts when debug mode is …
=> release: v0.6.6

CHANGELOG.md, configuration.go, example/example1/go.mod, example/opentelemetry/go.mod
Release 0.7.0 for go-sdk (re-versioned from 0.6.6) including:
- feat: fix and improve retries and rate limit handling. (https://github.com/openfga/go-sdk/pull/176)
The SDK now retries on network errors and the default retry handling has been fixed
for both the calls to the OpenFGA API and the API Token Issuer for those using ClientCredentials
The SDK now also respects the rate limit headers (`Retry-After`) returned by the server and will retry the request after the specified time.
If the header is not sent or on network errors, it will fall back to exponential backoff.
- feat: retry on network errors when calling the token issuer (https://github.com/openfga/go-sdk/pull/182)
- feat: add upport for server-side BatchCheck (https://github.com/openfga/go-sdk/pull/187)
- chore: log retry …
=> Release v0.7.0

CHANGELOG.md, client/client.go, client/client_test.go, configuration.go, example/example1/go.mod, example/example1/go.sum, example/opentelemetry/go.mod, go.mod, go.sum
- Update Changelog for v0.7.1
- Update config to new version
- Resolves issue where if number of checks exceeds MaxParallelRequests * MaxBatchSize a stall occurs. Ensures that all checks are processed
- Added additional test coverage related to this issue to prevent recurrence of similar issues.
- remove private method from interface to allow mocking
- closes https://github.com/openfga/go-sdk/issues/191
- closes https://github.com/openfga/go-sdk/issues/192
- https://github.com/openfga/sdk-generator/pull/532
=> release: v0.7.1

.github/workflows/semgrep.yaml
Potential fix for [https://github.com/openfga/go-sdk/security/code-scanning/1](https://github.com/openfga/go-sdk/security/code-scanning/1)
To fix the problem, you should add a `permissions` block to the job definition for `semgrep` in `.github/workflows/semgrep.yaml`. The minimal required permission for running Semgrep and checking out code is typically `contents: read`, which allows the job to read repository contents but not modify them. This block should be added directly under the job name (`name: Scan`) and before other job-level keys such as `runs-on`. No additional imports or definitions are required; this is a YAML configuration change.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> chore(ci): restrict semgrep workflow permissions to only read contents
